In [2]:
import pandas as pd
import numpy as np


In [50]:
from sklearn.linear_model import LinearRegression

In [51]:
df = np.round(pd.read_csv('50_Startups.csv')[['R&D Spend','Administration','Marketing Spend','Profit']]/10000)
np.random.seed(9)
df = df.sample(5)
df

R&D Spend  Administration  Marketing Spend  Profit
21        8.0            15.0             30.0    11.0
37        4.0             5.0             20.0     9.0
2        15.0            10.0             41.0    19.0
14       12.0            16.0             26.0    13.0
44        2.0            15.0              3.0     7.0

In [52]:
df = df.iloc[:,0:-1]
df.head()


R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        4.0             5.0             20.0
2        15.0            10.0             41.0
14       12.0            16.0             26.0
44        2.0            15.0              3.0

In [53]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[-1,-1] = np.nan

C:\Users\devul\AppData\Local\Temp\ipykernel_18424\766688332.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[1,0] = np.nan
C:\Users\devul\AppData\Local\Temp\ipykernel_18424\766688332.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[3,1] = np.nan
C:\Users\devul\AppData\Local\Temp\ipykernel_18424\766688332.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[-1,-1] = np.nan


In [54]:
df.head()

R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        NaN             5.0             20.0
2        15.0            10.0             41.0
14       12.0             NaN             26.0
44        2.0            15.0              NaN

In [55]:
df0 = pd.DataFrame()

df0['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration'] = df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend'] = df['Marketing Spend'].fillna(df['Marketing Spend'].mean())

In [56]:
df0

R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37       9.25            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.25            26.00
44       2.00           15.00            29.25

In [57]:
# Remove the col1 imputed value
df1 = df0.copy()

df1.iloc[1,0] = np.nan

df1

R&D Spend  Administration  Marketing Spend
21        8.0           15.00            30.00
37        NaN            5.00            20.00
2        15.0           10.00            41.00
14       12.0           11.25            26.00
44        2.0           15.00            29.25

In [58]:

X = df1.iloc[[0,2,3,4],1:3]
X

Administration  Marketing Spend
21           15.00            30.00
2            10.00            41.00
14           11.25            26.00
44           15.00            29.25

In [59]:
y = df1.iloc[[0,2,3,4],0]
y

21     8.0
2     15.0
14    12.0
44     2.0
Name: R&D Spend, dtype: float64

In [60]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[1,1:].values.reshape(1,2))

D:\new folder\envs\py312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([23.14158651])

In [61]:
df1.iloc[1,0] = 23.14

In [62]:
df1

R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.14            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.25            26.00
44       2.00           15.00            29.25

In [63]:
# Remove the col2 imputed value

df1.iloc[3,1] = np.nan

df1

R&D Spend  Administration  Marketing Spend
21       8.00            15.0            30.00
37      23.14             5.0            20.00
2       15.00            10.0            41.00
14      12.00             NaN            26.00
44       2.00            15.0            29.25

In [64]:
# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[[0,1,2,4],[0,2]]
X

R&D Spend  Marketing Spend
21       8.00            30.00
37      23.14            20.00
2       15.00            41.00
44       2.00            29.25

In [65]:
y = df1.iloc[[0,1,2,4],1]
y

21    15.0
37     5.0
2     10.0
44    15.0
Name: Administration, dtype: float64

In [66]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

D:\new folder\envs\py312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.06331285])

In [67]:
df1.iloc[3,1] = 11.06

In [68]:
df1

R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.14            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.06            26.00
44       2.00           15.00            29.25

In [69]:
# Remove the col3 imputed value
df1.iloc[4,-1] = np.nan

df1


R&D Spend  Administration  Marketing Spend
21       8.00           15.00             30.0
37      23.14            5.00             20.0
2       15.00           10.00             41.0
14      12.00           11.06             26.0
44       2.00           15.00              NaN

In [70]:
# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[0:4,0:2]
X

R&D Spend  Administration
21       8.00           15.00
37      23.14            5.00
2       15.00           10.00
14      12.00           11.06

In [71]:
y = df1.iloc[0:4,-1]
y

21    30.0
37    20.0
2     41.0
14    26.0
Name: Marketing Spend, dtype: float64

In [72]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[4,0:2].values.reshape(1,2))


D:\new folder\envs\py312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([31.56351448])

In [73]:
df1.iloc[4,-1] = 31.56

In [74]:
df1

R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.14            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.06            26.00
44       2.00           15.00            31.56

In [75]:
df1 - df0

R&D Spend  Administration  Marketing Spend
21       0.00            0.00             0.00
37      13.89            0.00             0.00
2        0.00            0.00             0.00
14       0.00           -0.19             0.00
44       0.00            0.00             2.31

In [76]:
df2 = df1.copy()

df2.iloc[1,0] = np.nan

df2

R&D Spend  Administration  Marketing Spend
21        8.0           15.00            30.00
37        NaN            5.00            20.00
2        15.0           10.00            41.00
14       12.0           11.06            26.00
44        2.0           15.00            31.56

In [77]:
X = df2.iloc[[0,2,3,4],1:3]
y = df2.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[1,1:].values.reshape(1,2))

D:\new folder\envs\py312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([23.78627207])

In [78]:
df2.iloc[1,0] = 23.78

In [79]:
df2.iloc[3,1] = np.nan
X = df2.iloc[[0,1,2,4],[0,2]]
y = df2.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[3,[0,2]].values.reshape(1,2))

D:\new folder\envs\py312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.22020174])

In [80]:
df2.iloc[3,1] = 11.22

In [81]:
df2.iloc[4,-1] = np.nan

X = df2.iloc[0:4,0:2]
y = df2.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[4,0:2].values.reshape(1,2))

D:\new folder\envs\py312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([38.87979054])

In [82]:
df2.iloc[4,-1] = 31.56

In [83]:
df2


R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.78            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.22            26.00
44       2.00           15.00            31.56

In [84]:
df2 - df1

R&D Spend  Administration  Marketing Spend
21       0.00            0.00              0.0
37       0.64            0.00              0.0
2        0.00            0.00              0.0
14       0.00            0.16              0.0
44       0.00            0.00              0.0

In [85]:
df3 = df2.copy()

df3.iloc[1,0] = np.nan

df3


R&D Spend  Administration  Marketing Spend
21        8.0           15.00            30.00
37        NaN            5.00            20.00
2        15.0           10.00            41.00
14       12.0           11.22            26.00
44        2.0           15.00            31.56

In [86]:
X = df3.iloc[[0,2,3,4],1:3]
y = df3.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[1,1:].values.reshape(1,2))

D:\new folder\envs\py312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([24.57698058])

In [87]:
df3.iloc[1,0] = 24.57

In [88]:
df3.iloc[3,1] = np.nan
X = df3.iloc[[0,1,2,4],[0,2]]
y = df3.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[3,[0,2]].values.reshape(1,2))

D:\new folder\envs\py312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.37282844])

In [89]:
df3

R&D Spend  Administration  Marketing Spend
21       8.00            15.0            30.00
37      24.57             5.0            20.00
2       15.00            10.0            41.00
14      12.00             NaN            26.00
44       2.00            15.0            31.56

In [112]:
df3.iloc[3,1] = 11.37

In [113]:
df3.iloc[4,-1] = np.nan

X = df3.iloc[0:4,0:2]
y = df3.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[4,0:2].values.reshape(1,2))

D:\new folder\envs\py312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([45.53976417])

In [114]:
df3.iloc[4,-1] = 45.53

In [115]:
df3

R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      24.57            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.37            26.00
44       2.00           15.00            45.53

In [116]:
df2.iloc[3,1] = 11.22

In [117]:
df3 - df2

R&D Spend  Administration  Marketing Spend
21       0.00            0.00             0.00
37       0.79            0.00             0.00
2        0.00            0.00             0.00
14       0.00            0.15             0.00
44       0.00            0.00            13.97

In [118]:
df4 = df3.copy()

df4.iloc[1,0] = np.nan

df4

R&D Spend  Administration  Marketing Spend
21        8.0           15.00            30.00
37        NaN            5.00            20.00
2        15.0           10.00            41.00
14       12.0           11.37            26.00
44        2.0           15.00            45.53

In [119]:
X = df4.iloc[[0,2,3,4],1:3]
y = df4.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df4.iloc[1,1:].values.reshape(1,2))

D:\new folder\envs\py312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([26.98977176])

In [120]:
df4.iloc[1,0]=26.98977176

In [121]:
df4

R&D Spend  Administration  Marketing Spend
21   8.000000           15.00            30.00
37  26.989772            5.00            20.00
2   15.000000           10.00            41.00
14  12.000000           11.37            26.00
44   2.000000           15.00            45.53

In [122]:
df4.iloc[3,1] = np.nan
X = df4.iloc[[0,1,2,4],[0,2]]
y = df4.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df4.iloc[3,[0,2]].values.reshape(1,2))

D:\new folder\envs\py312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([12.75132159])

In [123]:
df4

R&D Spend  Administration  Marketing Spend
21   8.000000            15.0            30.00
37  26.989772             5.0            20.00
2   15.000000            10.0            41.00
14  12.000000             NaN            26.00
44   2.000000            15.0            45.53

In [124]:
df4.iloc[3,1]=12.75132159

In [125]:
df4

R&D Spend  Administration  Marketing Spend
21   8.000000       15.000000            30.00
37  26.989772        5.000000            20.00
2   15.000000       10.000000            41.00
14  12.000000       12.751322            26.00
44   2.000000       15.000000            45.53

In [126]:
df4.iloc[4,-1] = np.nan

X = df4.iloc[0:4,0:2]
y = df4.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df4.iloc[4,0:2].values.reshape(1,2))

D:\new folder\envs\py312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([68.68143171])

In [127]:
df4.iloc[4,-1]=68.68143171

In [130]:
df4-df3

R&D Spend  Administration  Marketing Spend
21   0.000000        0.000000         0.000000
37   2.419772        0.000000         0.000000
2    0.000000        0.000000         0.000000
14   0.000000        1.381322         0.000000
44   0.000000        0.000000        23.151432

In [135]:
df5 = df4.copy()

df5.iloc[1,0] = np.nan

df5

R&D Spend  Administration  Marketing Spend
21        8.0       15.000000        30.000000
37        NaN        5.000000        20.000000
2        15.0       10.000000        41.000000
14       12.0       12.751322        26.000000
44        2.0       15.000000        68.681432

In [136]:
X = df5.iloc[[0,2,3,4],1:3]
y = df5.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df5.iloc[1,1:].values.reshape(1,2))

D:\new folder\envs\py312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([26.68917576])

In [145]:
df5.iloc[1,0]=26.68917576

In [146]:
df5.iloc[3,1] = np.nan
X = df5.iloc[[0,1,2,4],[0,2]]
y = df5.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df5.iloc[3,[0,2]].values.reshape(1,2))

D:\new folder\envs\py312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([13.01883939])

In [139]:
df5

R&D Spend  Administration  Marketing Spend
21   8.000000            15.0        30.000000
37  26.689176             5.0        20.000000
2   15.000000            10.0        41.000000
14  12.000000             NaN        26.000000
44   2.000000            15.0        68.681432

In [147]:
df5.iloc[3,1]=13.01883939

In [148]:
df5

R&D Spend  Administration  Marketing Spend
21   8.000000       15.000000        30.000000
37  26.689176        5.000000        20.000000
2   15.000000       10.000000        41.000000
14  12.000000       13.018839        26.000000
44   2.000000       15.000000        70.836916

In [149]:
df5.iloc[4,-1] = np.nan

X = df5.iloc[0:4,0:2]
y = df5.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df5.iloc[4,0:2].values.reshape(1,2))

D:\new folder\envs\py312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([70.94019656])

In [150]:
df5.iloc[4,-1]=70.83691617

In [151]:
df5-df4

R&D Spend  Administration  Marketing Spend
21   0.000000        0.000000         0.000000
37  -0.300596        0.000000         0.000000
2    0.000000        0.000000         0.000000
14   0.000000        0.267518         0.000000
44   0.000000        0.000000         2.155484

In [153]:
df6 = df5.copy()

df6.iloc[1,0] = np.nan

df6

R&D Spend  Administration  Marketing Spend
21        8.0       15.000000        30.000000
37        NaN        5.000000        20.000000
2        15.0       10.000000        41.000000
14       12.0       13.018839        26.000000
44        2.0       15.000000        70.836916

In [154]:
X = df6.iloc[[0,2,3,4],1:3]
y = df6.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df6.iloc[1,1:].values.reshape(1,2))

D:\new folder\envs\py312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([26.70090908])

In [155]:
df6.iloc[1,0]=26.70090908

In [156]:
df6.iloc[3,1] = np.nan
X = df6.iloc[[0,1,2,4],[0,2]]
y = df6.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df6.iloc[3,[0,2]].values.reshape(1,2))

D:\new folder\envs\py312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([13.01977595])

In [157]:
df6.iloc[3,1]=13.01977595

In [158]:
df6.iloc[4,-1] = np.nan

X = df6.iloc[0:4,0:2]
y = df6.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df6.iloc[4,0:2].values.reshape(1,2))

D:\new folder\envs\py312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([70.84286797])

In [159]:
df6.iloc[4,-1]=70.84286797

In [160]:
df6-df5

R&D Spend  Administration  Marketing Spend
21   0.000000        0.000000         0.000000
37   0.011733        0.000000         0.000000
2    0.000000        0.000000         0.000000
14   0.000000        0.000937         0.000000
44   0.000000        0.000000         0.005952

In [161]:
df7= df6.copy()

df7.iloc[1,0] = np.nan

df7

R&D Spend  Administration  Marketing Spend
21        8.0       15.000000        30.000000
37        NaN        5.000000        20.000000
2        15.0       10.000000        41.000000
14       12.0       13.019776        26.000000
44        2.0       15.000000        70.842868

In [162]:
X = df7.iloc[[0,2,3,4],1:3]
y = df7.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df7.iloc[1,1:].values.reshape(1,2))

D:\new folder\envs\py312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([26.70097677])

In [163]:
df7.iloc[1,0]=26.70097677

In [164]:
df7.iloc[3,1] = np.nan
X = df7.iloc[[0,1,2,4],[0,2]]
y = df7.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df7.iloc[3,[0,2]].values.reshape(1,2))

D:\new folder\envs\py312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([13.01973212])

In [166]:
df7.iloc[3,1]=13.01973212

In [167]:
df7.iloc[4,-1] = np.nan

X = df7.iloc[0:4,0:2]
y = df7.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df7.iloc[4,0:2].values.reshape(1,2))

D:\new folder\envs\py312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([70.84258964])

In [168]:
df7.iloc[4,-1]=70.84258964

In [171]:
df7-df6

R&D Spend  Administration  Marketing Spend
21   0.000000        0.000000         0.000000
37   0.000068        0.000000         0.000000
2    0.000000        0.000000         0.000000
14   0.000000       -0.000044         0.000000
44   0.000000        0.000000        -0.000278