In [4]:
import numpy as np
import pandas as pd
import pickle

In [36]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [47]:
# giving user input 
#pclass/gender/age/Sibsp/Parch/Fare/Embarked
test_input = np.array([3, 'male', 7.0, 0, 0, 10.5, 'Q'],dtype=object).reshape(1,7)


In [48]:
test_input

array([[3, 'male', 7.0, 0, 0, 10.5, 'Q']], dtype=object)

In [49]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))


D:\new folder\envs\py312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [50]:
test_input_sex

array([[0., 1.]])

In [51]:
test_input_embarked

array([[0., 1., 0.]])

In [52]:
test_input_age = test_input[:,2].reshape(1,1)


In [53]:
test_input_age

array([[7.0]], dtype=object)

In [54]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)


In [55]:
test_input_transformed 

array([[3, 0, 0, 10.5, 7.0, 0.0, 1.0, 0.0, 1.0, 0.0]], dtype=object)

In [56]:
clf.predict(test_input_transformed)


array([0])